### ISSUE TITLE
SWIFT_VERSION unassigned in installation?

### ISSUE THREAD

**Issue by schmidtwmark** [flutter-devs/qr_utils#5]
After adding the dependency to my pubspec.yaml and running `flutter packages get`, I try to run my app and I get this fun error:

```
 Downloading dependencies

    -> Installing Flutter (1.0.0)

    -> Installing qr_utils (0.1.4)

    -> Installing shared_preferences (0.0.1)
      - Running pre install hooks
    [!] Unable to determine Swift version for the following pods:

    - `qr_utils` does not specify a Swift version and none of the targets (`Runner`) integrating it have the
    `SWIFT_VERSION` attribute set. Please contact the author or set the `SWIFT_VERSION` attribute in at least one of the
    targets that integrate this pod.

    /usr/local/Cellar/cocoapods/1.7.0/libexec/gems/cocoapods-1.7.0/lib/cocoapods/installer/xcode/target_validator.rb:122:
    in `verify_swift_pods_swift_version'
    /usr/local/Cellar/cocoapods/1.7.0/libexec/gems/cocoapods-1.7.0/lib/cocoapods/installer/xcode/target_validator.rb:37:i
    n `validate!'
    /usr/local/Cellar/cocoapods/1.7.0/libexec/gems/cocoapods-1.7.0/lib/cocoapods/installer.rb:578:in `validate_targets'
    /usr/local/Cellar/cocoapods/1.7.0/libexec/gems/cocoapods-1.7.0/lib/cocoapods/installer.rb:158:in `install!'
    /usr/local/Cellar/cocoapods/1.7.0/libexec/gems/cocoapods-1.7.0/lib/cocoapods/command/install.rb:51:in `run'
    /usr/local/Cellar/cocoapods/1.7.0/libexec/gems/claide-1.0.2/lib/claide/command.rb:334:in `run'
    /usr/local/Cellar/cocoapods/1.7.0/libexec/gems/cocoapods-1.7.0/lib/cocoapods/command.rb:52:in `run'
    /usr/local/Cellar/cocoapods/1.7.0/libexec/gems/cocoapods-1.7.0/bin/pod:55:in `<top (required)>'
    /usr/local/Cellar/cocoapods/1.7.0/libexec/bin/pod:22:in `load'
    /usr/local/Cellar/cocoapods/1.7.0/libexec/bin/pod:22:in `<main>'

Error output from CocoaPods:
↳

    [!] Automatically assigning platform `ios` with version `8.0` on target `Runner` because no platform was specified.
    Please specify a platform for this target in your Podfile. See
    `https://guides.cocoapods.org/syntax/podfile.html#platform`.

Error running pod install
Error launching application on iPhone Xʀ.

```
I've searched around and tried some things out so I figured I'd make an issue and see if anyone knows how to fix. I can get the "specifying target version" error to go away by uncommenting a line in the podfile, but I can't get past the SWIFT_VERSION error.

**Comment by rgbinnovation** [comment]
Open your iOS project in Xcode, add a single Swift file, name it whatever, and Swift will be added to the project. You can now set SWIFT_VERSION. But, the plugin won't run. Depreciated code.
